### PR TITLE
Fix ICU78 FormDateTimeSelect issues with zh_Hant locale

### LINKED ISSUE #307: FormDateTimeSelect throws error with zh_Hant locale and ICU78
### Bug Report

I'm getting errors running the test suite caused by the pattern parser in `FormDateTimeSelect`

|    Q        |   A
|------------ | ------
| Version(s)  | 3.23.0

#### Summary

With ICU78 the `IntlDateFormatter::getPattern()` returns `y/M/dBh:mm:ss [z]` for the `zh_Hant` locale. Because there is no delimiter between the `d` and `h`, the parsed result is missing the `hours` key, causing a TypeError.

#### Current behavior

```
PHPUnit 11.5.43 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.28
Configuration: /Users/matt/www/laminas-form/phpunit.xml.dist
Time: 00:00.986, Memory: 14.00 MB

There was 1 error:

1) LaminasTest\Form\View\Helper\FormDateTimeSelectTest::testRendersDatesOnlyWithNumericValuesInSelectOptions
TypeError: Laminas\Form\View\Helper\FormDateTimeSelect::getHoursOptions(): Argument #1 ($pattern) must be of type string, null given, called in /Users/matt/www/laminas-form/src/View/Helper/FormDateTimeSelect.php on line 109

/Users/matt/www/laminas-form/src/View/Helper/FormDateTimeSelect.php:292
/Users/matt/www/laminas-form/src/View/Helper/FormDateTimeSelect.php:109
/Users/matt/www/laminas-form/test/View/Helper/FormDateTimeSelectTest.php:325
```

#### How to reproduce

Upgrade to the latest version of the `intl` extension:

```
php --ri intl

intl

Internationalization support => enabled
ICU version => 78.1
ICU Data version => 78.1
ICU TZData version => 2025b
ICU Unicode version => 17.0

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => Off => Off
```

Then run the tests.

#### Expected behavior

Tests pass

### PR DESCRIPTION
**Pull request by kynx**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Fixes #307

### CODE REVIEW

File: src/View/Helper/FormDateTimeSelect.php [hunk 1]
```diff
@@ -244,14 +248,21 @@ protected function parsePattern(bool $renderDelimiters = true): array
                 $result['minute'] = $value;
             } elseif ($noDelimiter && str_contains($value, 's')) {
                 $result['second'] = $value;
-            } elseif ($noDelimiter && stripos($value, 'a') !== false) {
-                // ignore ante/post meridiem marker
-                continue;
```
Comment (kynx) [inline src/View/Helper/FormDateTimeSelect.php:249]: This was causing a trailing `:` to be added after the minute selector - the numeric index was out of sync so it wasn't unset on line 146.

File: src/View/Helper/FormDateTimeSelect.php [hunk 2]
```diff
@@ -220,7 +224,7 @@ protected function parsePattern(bool $renderDelimiters = true): array
         }
 
         $pregResult = preg_split(
-            "/([ \-,.:\/]*'.*?'[ \-,.:\/]*)|([ \-,.:\/]+)/",
+            "/([ \-,.:0abvxz\/]*'.*?'[ \-,.:0abvxz\/]*)|([ \-,.:0abvxz\/]+)/i",
```
Comment (kynx) [inline src/View/Helper/FormDateTimeSelect.php:227]: See https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table

File: src/View/Helper/FormDateTimeSelect.php [hunk 3]
```diff
@@ -244,14 +248,21 @@ protected function parsePattern(bool $renderDelimiters = true): array
...
-                continue;
             } elseif ($renderDelimiters) {
-                $result[] = str_replace("'", '', $value);
+                $result[] = preg_replace("/['0abvxz[\]]/i", '', $value);
             }
         }
 
+        $valid = ['day', 'month', 'year', 'hour', 'minute'];
+        if (array_intersect($valid, array_keys($result)) !== $valid) {
+            throw new Exception\IntlException(sprintf(
```
Comment (froschdesign) [inline src/View/Helper/FormDateTimeSelect.php:258]: The exception is new, what was the result before?

Comment (Slamdunk) [reply src/View/Helper/FormDateTimeSelect.php:258]: `TypeError: Laminas\Form\View\Helper\FormDateTimeSelect::getHoursOptions(): Argument #1 ($pattern) must be of type string, null given`

So I'd say this is better

**Review by Slamdunk — APPROVED** [review]
